apiVersion: v1
kind: Pod
metadata:
  name: web-pod-vol
spec:
  containers:
    - name: web 
      image: nginx:alpine 
      ports:
      - containerPort: 80 
      volumeMounts: 
        - mountPath: / data
          name: my-data 
  volumes: 
   - name: my-data
     persistentVolumeClaim:
      claimName: my-data-claim