apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels: 
    app: wordpress

spec:
  replicas: 3
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      
      - name: wordpress
        image: wordpress:4.8-apache

        env:
        - name: WORDPRESS_DB_HOST
          value: database-service
        - name: WORDPRESS_DB_PASSWORD
          value: root

        ports:
        - containerPort: 80
          name: wordpress
